### ISSUE TITLE
uninitialized constant Geoip

### ISSUE THREAD

**Issue by blanchma** [priithaamer/geoip-rails#4]
> > Geoip
> > NameError: uninitialized constant Geoip
> >     from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:469:in `load_missing_constant'
> >     from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:106:in`rake_original_const_missing'
> >     from /usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/ext/module.rb:36:in `const_missing'
> >     from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:118:in`const_missing'
> >     from (irb):4

**Comment by blanchma** [comment]
Important: I'm running rails 2.3.12 and ruby 1.8.7
